-- 코드를 입력하세요
SELECT CC.CAR_ID, CC.CAR_TYPE, ROUND((1 - CAST(REPLACE(DP.DISCOUNT_RATE, '%', '') AS DECIMAL(10, 2)) / 100) * CC.DAILY_FEE * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CC JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE DP.DURATION_TYPE LIKE '30%' AND 
CC.CAR_TYPE IN ('SUV', '세단') AND 
((1 - CAST(REPLACE(DP.DISCOUNT_RATE, '%', '') AS DECIMAL(10, 2)) / 100)
 * CC.DAILY_FEE * 30) BETWEEN 500000 AND 2000000 AND
CC.CAR_ID NOT IN (
SELECT car_id FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE > '2022-10-30');
