WITH FRONTEND_SKILLS AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME 
FROM DEVELOPERS AS D INNER JOIN FRONTEND_SKILLS AS F
ON F.CODE & D.SKILL_CODE
ORDER BY ID ASC;