SELECT MR.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE AS MR
         JOIN REST_REVIEW AS RR
              ON MR.MEMBER_ID = RR.MEMBER_ID
WHERE MR.MEMBER_ID = (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
    LIMIT 1
    )
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;