SELECT M.YEAR, (M.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID FROM 
ECOLI_DATA JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
           MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS M
ON M.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC;