SELECT B.ID, FNI.FISH_NAME, B.MAX_LENGTH AS LENGTH
FROM FISH_NAME_INFO AS FNI JOIN (SELECT ORI.ID, FT.MAX_LENGTH, FT.FISH_TYPE
FROM FISH_INFO AS ORI JOIN (
    SELECT MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE FROM FISH_INFO GROUP BY FISH_TYPE) AS FT
ON ORI.FISH_TYPE = FT.FISH_TYPE AND ORI.LENGTH = FT.MAX_LENGTH) AS B
ON FNI.FISH_TYPE = B.FISH_TYPE;