SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_NAME_INFO AS FNI JOIN (SELECT ID, LENGTH, FISH_TYPE
FROM FISH_INFO 
WHERE (LENGTH, FISH_TYPE) IN (SELECT MAX(LENGTH), FISH_TYPE AS MAX_LENGTH FROM FISH_INFO GROUP BY FISH_TYPE)) AS FI
ON FNI.FISH_TYPE = FI.FISH_TYPE
ORDER BY ID ASC;